require('monolith.core.settings')
require('monolith.core.plugins')

require('impatient')

require('monolith.config.common')
require('monolith.config.tabby')
require('monolith.config.yabs')
require('monolith.config.wilder')
require('monolith.config.lualine')
require('monolith.config.easypick')
require('monolith.config.colorpicker')
require('monolith.config.sidebar')
require('monolith.config.scrollbar')
require('monolith.config.dap')
require('monolith.config.comment')
require('monolith.config.lsp')
require('monolith.config.lsp-server')
require('monolith.config.tree')
require('monolith.config.telescope')
require('monolith.config.minimap')
require('monolith.config.hydra')
require('monolith.config.alpha')
-- require('monolith.config.dashboard')
require('monolith.config.colorscheme')

require('monolith.core.mappings')
require('monolith.core.autocmd')
