-- local sysdep = require("utils.sysdep")
--
-- return {
--     {
--         'sainnhe/gruvbox-material',
--         lazy = false,
--         priority = 1000,
--         config = function()
--             vim.g.gruvbox_material_enable_italic = true
--             vim.g.gruvbox_material_background = 'hard'
--             vim.g.gurvbox_material_foreground = 'original'
--             vim.g.gurvbox_material_transparent_background = 1
--             vim.g.gruvbox_material_visual = 'reverse'
--             -- vim.cmd.colorscheme('gruvbox-material')
--         end
--     },
--     {
--         "ellisonleao/gruvbox.nvim",
--         priority = 1000,
--         opts = {
--             terminal_colors = true, -- add neovim terminal colors
--             undercurl = true,
--             underline = true,
--             bold = true,
--             italic = {
--                 strings = true,
--                 emphasis = true,
--                 comments = true,
--                 operators = false,
--                 folds = true,
--             },
--             strikethrough = true,
--             invert_selection = true,
--             invert_signs = false,
--             invert_tabline = false,
--             invert_intend_guides = false,
--             inverse = true, -- invert background for search, diffs, statuslines and errors
--             contrast = "", -- can be "hard", "soft" or empty string
--             palette_overrides = {},
--             overrides = {},
--             dim_inactive = false,
--             transparent_mode = true,
--         },
--         config = function()
--             vim.cmd.colorscheme('gruvbox')
--         end
--     }
-- }
return {}
